### ISSUE TITLE
Question: Dart to Kotlkin

### ISSUE THREAD

**Issue by sertunc** [olexale/mrz_parser#1]
Hello, How can I use this lib on my native andorid(kotlin) application. Thank you

**Comment by olexale** [comment]
Hi @sertunc,

I don't think this is possible unless you want to integrate Dart VM into your native app, which I highly recommend you not to do.
https://github.com/ZsBT/mrz-java is probably the SDK you're looking for.

Kind regards,
Oleksandr

**Comment by sertunc** [comment]
Thank you @olexale
