### ISSUE TITLE
cannot parse Some TD1 data in some countries, like Kenya.

### ISSUE THREAD

**Issue by vick-ram** [olexale/mrz_parser#14]
Cannot parse the data in some countries.

**Comment by olexale** [comment]
It's impossible to find out what's wrong without sample data.

[Here is the link](https://www.icao.int/publications/Documents/9303_p5_cons_en.pdf) to TD1 specification. Scroll down to page 13 and check whether the TD1 you are parsing conforms to the specification.

**Comment by olexale** [comment]
Without sample data, it is hard to tell what's wrong. I'm closing the issue, feel free to re-open it if you can provide more details.
