### ISSUE TITLE
Support for Algerian identity

### ISSUE THREAD

**Issue by haithemnini** [olexale/mrz_parser#15]
Hello, I would like to do an analysis of the Algerian identity card, the process takes longer than I expected

**Comment by olexale** [comment]
Please be more specific about what's wrong.

For me, the package parsed the MRZ correctly:
```dart
        final mrz = MRZParser.parse([
          'IDDZA2018537363<<<<<<<<<<<<<<<',
          '0006105M2210012DZA<<<<<<<<<<<2',
          'NINI<<HAITHEM<<<<<<<<<<<<<<<<<',
        ]);
```
instantiates the following object:
<img width="349" alt="Знімок екрана 2024-11-29 о 14 16 09" src="https://github.com/user-attachments/assets/e3f9e792-0ab1-4218-82e5-266029718999">

**Comment by olexale** [comment]
I'm closing this issue as seems like the Algerian identity card is supported. Feel free to re-open the issue with more context.
