### ISSUE TITLE
Can not parse passport with 8 character long passport number eg:- K9876543

### ISSUE THREAD

**Issue by kartikpateldev** [olexale/mrz_parser#2]
I am not able to parse below list of string which I get from one passport.
After debugging, I came to know that this package is not parsing below mrz code because it have passport number with 8 character log i.e 'K9876543'. If I change this passport number with 9 digit long than it will parse perfectly but not parses the 8 character long. Please fix it.

<String>[
  'P<UTOERIKSSON<<ANNA<MARIA<<<<<<<<<<<<<<<<<<<',
  'K9876543<8UTO8708243F2206219<<<<<<<<<<<<<<<6'
];

Thanks in advance,

**Comment by foxanna** [comment]
Hi Kartik, 
Thanks for reporting! It is indeed an issue inside the parser. I'll get back to you soon with the solution.

**Comment by foxanna** [comment]
Could you please check the new package version `1.1.0`?
Beware that `parse()` method now throws `MRZException` if parsing was unsuccessful. For silent parsing use `tryParse()`.

**Comment by kartikpateldev** [comment]
Thanks a lot @foxanna for fixing it. :100: :+1:
