### ISSUE TITLE
Document number hash mismatch

### ISSUE THREAD

**Issue by onalekitso** [olexale/mrz_parser#3]
Good I am happy to use your plugin but I have an issue with Botswana Passport. I have an error Document number hash mismatch. It has 9 characters of Document number BNO2574538BWA8208282M2206035107515512<<<<<78

Thank you in advance for your help

**Comment by foxanna** [comment]
According to Check Digit Calculations rules, the checksum of document number `BNO257453` should be `2`, which is what **MRZ parser** produces, but according to your example, `8` is expected. [More on check digits calculation](https://help.microblink.com/hc/en-us/articles/360007487833-MRTD-FAQ#h_9e88fca7-3174-4c93-a34d-3603ff06f2e8).

Here are calculations of the check digit for a document number from the example:
```
Input:	    B	 	N	 	O	 	2	 	5	 	7	 	4	 	5	 	3		
Value:	    11	 	23	 	24	 	2	 	5	 	7	 	4	 	5	 	3		
Weight:	    7	 	3	 	1	 	7	 	3	 	1	 	7	 	3	 	1		
Products:   77		69	 	24	 	14	 	15	 	7	 	28	 	15	 	3		
Sum:	    77	+	69	+	24	+	14	+	15	+	7	+	28	+	15	+	3	=	252
```
Division: 252 ÷ 10 = 25, remainder **2**. Thus the document number check digit is **2**.

**Comment by olexale** [comment]
@onalekitso , it seems that the library works as expected hence I'm closing the ticket.
Thanks, @foxanna!

**Comment by onalekitso** [comment]
I'm sorry for taking long to get back to you. Haven't used it again, have been held up on other things. Thank you for your response, and I appreciate the clarifications
