### ISSUE TITLE
French mrz

### ISSUE THREAD

**Issue by pierre-gancel** [olexale/mrz_parser#4]
like #3 I get *Document number hash mismatch*
Yet I think  this is because I use a French ID Card,
Any plans / recommendations on how to include them ?

**Comment by foxanna** [comment]
Hi @pierre-gancel, 
The plugin currently supports TD1, TD2, and TD3 travel document formats, as well as MRV-A and MRV-B visas.
Can you provide the rules used to compose the Document number hash in French documents?

**Comment by pierre-gancel** [comment]
Hi @foxanna,
Thank you for your quick reply,
Here is what [wikipedia](https://en.wikipedia.org/wiki/National_identity_card_(France)#Machine-readable_zone) gives me :

<img width="1071" alt="Screenshot 2020-11-23 at 09 02 27" src="https://user-images.githubusercontent.com/69810198/99939549-9dabd700-2d6a-11eb-805a-69bb0b9a901e.png">

**Comment by pierre-gancel** [comment]
Hi @foxanna ,

Hope you're well,
Just circling the wagon here, anything I could do to help ?

**Comment by foxanna** [comment]
Hi @pierre-gancel,
I appreciate your interest in improving this plugin.
This issue is on my TODO list, and hopefully, I will get back to you in the upcoming week.

**Comment by foxanna** [comment]
Hi @pierre-gancel,
We have released a new v.1.2.0. Please test and let us know if this issue can be closed.

**Comment by pierre-gancel** [comment]
It works like a charm,
Well done and a huge thank you :)

**Comment by foxanna** [comment]
Great news!
Thank you for filing an issue and providing additional information to enable the fix!
