### ISSUE TITLE
I/flutter (10738): Document number hash mismatch. If you think this is a mistake, please file an issue https://github.com/olexale/mrz_parser/issues

### ISSUE THREAD

**Issue by henouni** [olexale/mrz_parser#7]
Hi, 
thanks in advance,
I'm trying to read Mauritanian ID mrz with your plugin, But i got the error above,
So can you help me please.

**Comment by foxanna** [comment]
Hi @henouni,
Thanks for raising this!
It may be that Mauritanian ID documents have special rules that are not covered. Can you elaborate more on the input and the expected/actual output?

**Comment by olexale** [comment]
Hey folks. I'm closing the issue. Feel free to re-open it with additional details.
