### ISSUE TITLE
Error: LSTM requested, but not present!! Loading tesseract.

### ISSUE THREAD

**Issue by mobin-sk** [olexale/mrz_parser#8]
When I open scanner in iOS , it is not detecting MRZ code in the console it shows error as : 
`Error: LSTM requested, but not present!! Loading tesseract.`. 
Can you please  help me  to fix this issue ?

**Comment by foxanna** [comment]
Hi @mobin-sk,
The `mrz_parser` package is responsible for converting a simple list of `String` to an `MRZResult` object. But looking at your description, I guess the problem arises before `mrz_parser` is involved and comes from the [flutter_mrz_scanner](https://github.com/olexale/flutter_mrz_scanner) code.

**Comment by mobin-sk** [comment]
Thanks For Reply :
I Guess  `tesseract` Pod version should be upgraded to solve this issue.

**Comment by foxanna** [comment]
Hi @mobin-sk, I assume the proposed solution is destined for another package.
Do you think this issue can be closed?

**Comment by mobin-sk** [comment]
Okay
